### ISSUE TITLE
Deploy to streamlit

### ISSUE THREAD

**Issue by zhaihaojie** [SimonBlanke/tabular-data-explorer#1]
I want to deploy this to the streamlit clound for my friends to use. How should I do it? I have now forked the official example and modified the code to the following part, which does not work
```python
from search_data_explorer import SearchDataExplorer
"""
数据可视化
"""
sde = SearchDataExplorer()
sde.open()
````

**Comment by zhaihaojie** [comment]
i have solved it thanks

**Comment by SimonBlanke** [comment]
Hello @zhaihaojie,

could you share how you solved this issue?

**Comment by zhaihaojie** [comment]
Sorry, I’m only online now and saw this message. When I was solving the problem, I found that when I run the code locally, it can run, but it can’t run on the cloud. Then I checked your writing method and I saw that the open function of the SearchDataExplorer class is executed in the terminal. The following code:
```python
"streamlit run " + dname + "/streamlit_run.py " + arg1 + args + port_cmd
```
When deploying on the streamlit cloud, it should execute the streamlit_app.py in the code repository instead of the streamlit_run.py in the python module sde. The execution method should be the official recommended execution method
```python
streamlit run streamlit_app.py
```
So I modified the code and directly imported the code of the app part I needed, as follows
```python
from search_data_explorer.tde_streamlit import app
import streamlit as st
import pandas as pd
app(search_data=None, plots=None)
```
 After that, I also encountered some problems. For example, when I downloaded the dependencies required by the module search_data_explorer, it missed two libraries hiplot and seaborn, which caused the runtime to prompt that these modules were missing. After I downloaded the environment dependencies, I exported them to requirements.txt and pushed them again. repository after restarting the streamlit app then it works fine

Finally, thank you very much for this small tool you wrote and the algorithm library gfo you wrote. I use this algorithm library to optimize the parameters of the strategy written by the backtrader library. The effect is much better than using option. At present, I hope it can support multi-process operation. I am currently using multiprocessing to work with multi-processes and I am quite satisfied with the speed, but I feel that there is still room for improvement, but thank you very much for this algorithm library

**Comment by SimonBlanke** [comment]
Hello @zhaihaojie,

thank you for this detailed guide to your solution! :-)

But be aware that:
```python
from search_data_explorer.tde_streamlit import app
```
is not part of the public API, which means that it might change in future versions. In those cases it is advised to fix the version you are using to the current one (v0.4.0). This avoids that you get breaking changes from newer versions.

It is nice to see, that you are using my GFO library as well. If you want to utilize multiprocessing for your optimization runs you can use my other package called [Hyperactive](https://github.com/SimonBlanke/Hyperactive). It was originally designed to tune hyperparameters, but can be used for a large variety of problems. It is build on top of GFO, has a very similar API but has more features. (GFO is basically a optimization backend)
